### ISSUE TITLE
Limitations in the number of occurrences

### ISSUE THREAD

**Issue by afilazzola** [DataDrivenEcologicalSynthesis/WeirdestSpeciesCombination#14]
**Problems**:
- There is close to 500 k observations within the Toronto boundary. GBIF allows downloads in batches of 500 with a maximum of 200,000 / day.  Too many for DL and takes a long time even smaller batches. 
- The Toronto boundary is uneven, based on rounding lat & lon, there is also the lake in the way. Need to create polygon that is comparable to other cities.

**Comment by scisus** [comment]
I'm fine choosing a box or circle of the same size and centering it over each city. We get to define the radius of weird and it can be "within x km of the city center." I don't think the water matters from a weird-defining perspective - it's just a spot where there are (many) fewer observations. 

As for the "two many observations" part, what if we started with a radius of 5km? That's how far people typically can walk in an hour.

**Comment by BenMerSci** [comment]
Anyone know of a place to download city delimitation polygons?

**Comment by scisus** [comment]
No, but what would we use them for?

**Comment by BenMerSci** [comment]
Just thought that we could work with the "official" city delimitation instead of an arbitrary buffer around it. This way we would be comparing the actual difference in the cities, and it won't encompass other area that don't really belong to the city? Unless we want to include some more natural habitat to the analysis?

**Comment by BenMerSci** [comment]
[@afilazzola comment](https://github.com/orgs/DataDrivenEcologicalSynthesis/teams/weirdestspeciescombination/discussions/6/comments/4)

**Comment by BenMerSci** [comment]
Related to [@afilazzola ](https://github.com/orgs/DataDrivenEcologicalSynthesis/teams/weirdestspeciescombination/discussions/6/comments/4) reply, using the city polygons might standardize the method in a way. (Won't have all the same area, but we will know exactly what they represent, and can be compared as the actual cities)

**Comment by cdrobich** [comment]
I think the issue of using the city boundary, rather than a set area of our choosing, is that larger cities will probably have more observations than a geographically smaller city. It limits our ability to compare among cities somewhat.

**Comment by BenMerSci** [comment]
I agree, but I would've thought there would be a way to control for the area of each cities in the analysis. (Note that I'm really not that good with statistical analysis that are not simple/multiple linear regression, mixed models haha..), thus making the city polgyons more user friendly than delimiting arbitrary polygons.

**Comment by cdrobich** [comment]
True, I guess it totally depends on what we end up being interested in (like, the response variable), because if we do know the area of a city we could treat it as a random effect to try to account for it.

**Comment by afilazzola** [comment]
I think we have resolved this by using smaller quadrats rather than large areas around cities
