### ISSUE TITLE
Why only urban areas?

### ISSUE THREAD

**Issue by scisus** [DataDrivenEcologicalSynthesis/WeirdestSpeciesCombination#16]
Should we include non-urban areas?

We chose (near) urban areas because of sampling density and human interest.

But it might be interesting to include non-urban areas *near* cities as comparisons.

**Comment by cdrobich** [comment]
I think it makes sense to begin by only looking at a certain area of multiple cities to refine our approach. If it works well we could do an "urban vs rural" comparison

**Comment by afilazzola** [comment]
I believe we resolved this with the transect idea
