### ISSUE TITLE
What is weird?

### ISSUE THREAD

**Issue by scisus** [DataDrivenEcologicalSynthesis/WeirdestSpeciesCombination#18]
How exactly are we defining weird?

Thoughts from the group included 
- defining a normal and seeing what would violate that
- what makes you say "whoa!"
- trait ordination and seeing which assemblages are the widest range of traits in that space

How are we handling non-native species? Does the dataset we're using include them?

**Comment by BenMerSci** [comment]
We settled on the extreme trait in plant communities.
