### ISSUE TITLE
What about a city would make it have weird(er) species assemblages?

### ISSUE THREAD

**Issue by scisus** [DataDrivenEcologicalSynthesis/WeirdestSpeciesCombination#19]
I think that @BenMerSci 's idea about adding other layers like climate might be useful for answering this question (if we decide to pursue it.)

Group discussion pointed out that city connectivity (e.g. ports) might matter.

I think that Vancouver might win because so many kinds of plants can survive it's mild climate. But that might depend on how many observations got made at the Montreal Botanical Gardens!

**Comment by BenMerSci** [comment]
Closing that since we're not going to add any climatic variables finally!
