### ISSUE TITLE
Match TRY and gbif species

### ISSUE THREAD

**Issue by scisus** [DataDrivenEcologicalSynthesis/WeirdestSpeciesCombination#28]
Associate TRY identifiers with species occurrences from gbif

**Comment by BenMerSci** [comment]
Do you mean associate the name from gbif occurences to the name in TRY?

**Comment by scisus** [comment]
Yes, I'm about to finish this.

**Comment by BenMerSci** [comment]
Did the gbif_parse() helped to remove the authority?

**Comment by scisus** [comment]
gbif_parse did remove the authority, but a more thorough cleaning pipeline could be developed - maybe in open refine? There seem to be some species names that have duplication within them (e.g. Betula alleghaniensis alleghaniensis) and NA entries.
