### ISSUE TITLE
Match species Master list to TRY species list

### ISSUE THREAD

**Issue by scisus** [DataDrivenEcologicalSynthesis/WeirdestSpeciesCombination#39]
example pipeline for matching TRY accession numbers built for Toronto in https://github.com/DataDrivenEcologicalSynthesis/WeirdestSpeciesCombination/pull/37

Extend to all cities.

**Comment by cdrobich** [comment]
Match the species to the TRY number so that we can pull the requests

**Comment by BenMerSci** [comment]
Is it normal that some species have more than one AccSpeciesID?
@cdrobich @scisus @afilazzola

**Comment by cdrobich** [comment]
Oh no, I’ve never actually used TRY before so I’m not sure. Is it happening with a lot of species?

**Comment by BenMerSci** [comment]
It's just that I have let say the MasterSpeciesList,
I joined the MasterSpeciesList with the TRY_SpeciesList by Species names that is already in our data folder,
So now I have a dataframe of the Species name with the AccSpeciesID,
If I unique that dataframe by the species name I have less row of  the dataframe which means that some species occurs in that dataframe more than one time, so they have different info the AccSpeciesID columns...

Not sure if i'm clear?? haha
