### ISSUE TITLE
Clean species Master list

### ISSUE THREAD

**Issue by scisus** [DataDrivenEcologicalSynthesis/WeirdestSpeciesCombination#41]
Initial tidying in matchGbifDataTry.R

https://github.com/DataDrivenEcologicalSynthesis/WeirdestSpeciesCombination/issues/28#issuecomment-636500769

**Comment by cdrobich** [comment]
Using OpenRefine, clean the data by removing variants/subspecies etc., separating Genus and species into separate columns, and removing duplicates/misspellings/NAs
