### ISSUE TITLE
Submit TRY request for species on the Master list

### ISSUE THREAD

**Issue by scisus** [DataDrivenEcologicalSynthesis/WeirdestSpeciesCombination#42]
Requires cleaned gbif species names (#41) and accession numbers (#39) and list of finalized traits (#34).

**Comment by cdrobich** [comment]
Submit requests to TRY for traits: include common traits i.e. specific leaf area, leaf thickness, number of flowers, number of seeds etc. 

This should take about 30 - 60 minutes, as it will require 10 submissions

**Comment by scisus** [comment]
This will use data/tryAccession/accessionMaster.csv and data/tryTraitsSelection.csv

**Comment by cdrobich** [comment]
Looking through and "accessionMaster.csv" is incorrect because it contains all of the duplicates species. I will pull all of the codes using the file where duplicates have been removed and update the  getTRY_ids script to indicate this step

**Comment by BenMerSci** [comment]
Yes I don't think accessionMaster.csv was updated.
We just need to run the file SpeciesList_TRY_join.csv in the script getTRY_ids.r.

**Comment by cdrobich** [comment]
I fixed it and am putting in the requests now!
