### ISSUE TITLE
Reduce the species Master list to 10,000

### ISSUE THREAD

**Issue by cdrobich** [DataDrivenEcologicalSynthesis/WeirdestSpeciesCombination#47]
<strike>WINNOW</strike> REDUCE THAT LIST

Get it down to 10, 000 species, using an (arbitrary) cut off of occurrences until we're below 10,000 species

**Comment by afilazzola** [comment]
To winnow that list we need to set a threshold 11 occurrences. Is that cool?

**Comment by cdrobich** [comment]
Sounds good to me! Actually a bit lower than I expected tbh

**Comment by BenMerSci** [comment]
# > 11 or >= 11?

**Comment by afilazzola** [comment]
> 11

**Comment by afilazzola** [comment]
lol... stupid formating `> 11`

**Comment by BenMerSci** [comment]
The MasterSpeciesList is already < 10 000 species..
Do we still remove the species that occurre less than 11 time?

**Comment by BenMerSci** [comment]
Every city combine, we have 3702 species in the dataset.

**Comment by afilazzola** [comment]
I think I was summing the count of occurrences rather than the number of unique spp
We are already under the 10,000 amount!
