### ISSUE TITLE
TRY traits to retrieve

### ISSUE THREAD

**Issue by cdrobich** [DataDrivenEcologicalSynthesis/WeirdestSpeciesCombination#49]
Uploaded a .csv of potential traits to pull for the trait requests - tried to have a variety of options that should have enough data. Just wanted people's input on it before requesting the data

**Comment by BenMerSci** [comment]
I would also suggest these: 
- Plant height generative
- Plant height vegetative
- Leaf thickness
- Leaf petiole length
