### ISSUE TITLE
Getting TRY data into GitHub

### ISSUE THREAD

**Issue by cdrobich** [DataDrivenEcologicalSynthesis/WeirdestSpeciesCombination#57]
We got the TRY data for the first request (1000 species) as a .txt file. It came with a readMe that makes it easy to get this data into R and write a .csv, however the .csv is too large for GitHub. It is over 2 mil rows, or 1081GB (limit for github is 25GB). I think we have to make some kind of loop to break it down into small enough .csv (quick math of 1081/25 = ~73 .csvs). Or someone who is better at this than me can find a work around?

To make it accessible for everyone I will share the TRY data email with everyone.

**Comment by BenMerSci** [comment]
Currently scripting something to take care of loading the files and tidying them and saving them into appropriate .csv files

**Comment by scisus** [comment]
I'll hopefully be able to pick up where you left off first thing tomorrow.

**Comment by afilazzola** [comment]
The repo limit on Github is 25GB, but the per-file limit is actually only 100 mb. 

Is there a typo somewhere? 1081 GB is over 1 terabyte in size. That is a truly gigantic CSV file

**Comment by cdrobich** [comment]
YUP there is, everything up there is wrong lol. I did it last night when I was tired, sorry.  The csv is 1.03 GB. When I tried to upload the file github said it was too large but 1GB is way more manageable

**Comment by scisus** [comment]
Closed by https://github.com/DataDrivenEcologicalSynthesis/WeirdestSpeciesCombination/pull/59#pullrequestreview-423571406
