### ISSUE TITLE
Final figures

### ISSUE THREAD

**Issue by cdrobich** [DataDrivenEcologicalSynthesis/WeirdestSpeciesCombination#66]
Place to brainstorm and organize figures

1. Histogram showing SLA distribution among the 6 cities
    * Do we also want to do this by quadrat?

2. List of weird species (5th and 95th quantiles)
    * By city?
    * By quadrats across cities?
    * Quadrats within each city?
    * All species? 

3. How to illustrate differences in weirdness within a city

4. How to illustrate differences in weirdness among all cities

**Comment by cdrobich** [comment]
I really like the violin plots @scisus made to illustrate differences in SLA among the cities!

**Comment by BenMerSci** [comment]
Do we start with the violin figures to show that there is variation among cities, 
then we proceed with a plot of multiple histogram with 1 row and 6 columns to show how the actual trait is, then proceed with a plot with multiplte histogram ( 6 columns for every city and 5 row for each quadrat) to show how they vary with the gradient ?

**Comment by cdrobich** [comment]
Sure! We can start with:
1) the histogram showing all the traits x city (illustrates the variation in SLA among the cities)
2) weird species within each city - we can "zoom in" to each city to show the variation & the list of species that are weird (maybe we take the two species that are the extremes of the spectrum within each city and show what they look like to illustrate this?) (if we have time we can also see how many times these species occur together within each quadrat) 
3) a comparison of weirdness among the quadrats in the city (std x quadrat, so like a violin plot or a jitter plot?), then we can zoom out
4) differences among quadrats x cities. 
Or we move the histogram that shows the total differences among the cities to right before point 4 and start with the weird species list.
