### ISSUE TITLE
To do for tomorrow:

### ISSUE THREAD

**Issue by cdrobich** [DataDrivenEcologicalSynthesis/WeirdestSpeciesCombination#88]
1. Compare std among the quadrats (so we can say which one is the weirdest i.e. within city comparison)

2. Compare the community composition (species list) among cities and determine how much overlap there is (e.g. are 90% of the species in each city the same?)

3. Figure out the extreme ends of the traits within each city? (like are they all Juniper vs Impatiens?)

4. Make a species richness x quadrat barchart

5. Assign parts to folks & write up the scripts etc.

**Comment by BenMerSci** [comment]
I,ll do 4. right now

**Comment by scisus** [comment]
I'll get on 1 :)

**Comment by scisus** [comment]
3 should be answered by `scripts/calculate_most_extreme_species.r`

**Comment by scisus** [comment]
2 is answered by `scripts/speciescombinations.r`
```
# Percent of a city's species that are in the set of species that occur in all cities
# City      percent_common
# <chr>              <dbl>
# 1 Winnipeg           16.4
# 2 Edmonton            9.15
# 3 Halifax             5.11
# 4 Toronto             4.31
# 5 Montreal            3.56
# 6 Vancouver           2.10
```

55 species total in common among all cities.

**Comment by scisus** [comment]
> 3 should be answered by `scripts/calculate_most_extreme_species.r`

Related, the 2 most normal species (sla = global median sla) are

 ```
            species TraitName    value diff
1   Senecio viscosus       SLA 22.46667    0
2 Sherardia arvensis       SLA 22.46667    0
```

**Comment by cdrobich** [comment]
Just following up, @scisus did you also do number 1?
